### ISSUE TITLE
Needs excludes

### ISSUE THREAD

**Issue by Tabiskabis** [RichKMLS/Old-Reddit-Redirect#2]
Reddit has a "no participation" old-style subdomain that needs to be excluded:
`// @exclude https://np.reddit.com/*`
  
But apparently, there are [more such domains](https://old.reddit.com/r/help/comments/2dj6md/the_reddit_subdomains_iuredditcom_ja_no_np_etc/) (incomplete list).  
So actually it might be best to exclude any 2-character-subdomain.reddit.com

**Comment by RichKMLS** [comment]
Great catch!
