### ISSUE TITLE
i.redd.it and gallery URLs

### ISSUE THREAD

**Issue by egb116** [RichKMLS/Old-Reddit-Redirect#3]
I think there are a few more URL patterns to account for.  These were tested on Safari 16.6 (18615.3.12.11.2) on MacOS 13.5 (22G74) with Userscripts for Safari Version 4.4.3 (74) in an incognito window.  Here are some examples, but I tried a few additional links with the same results.

[https://i.redd.it/zv02loj5yejb1.png](https://i.redd.it/zv02loj5yejb1.png)

redirects (very strangely!) to 

[https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fi.redd.it%2Fzv02loj5yejb1.png](https://old.reddit.com/r/funny/comments/media/nice_hat/?url=https%3A%2F%2Fi.redd.it%2Fzv02loj5yejb1.png)

I wonder if that /r/funny post is something to do with my browser or if it's a reddit quirk?  (That's why I was using incognito, to hopefully rule out anything on my end.)  It seemed like all i.redd.it links redirected to that same post.

Also,

[https://www.reddit.com/gallery/15wdvhr](https://www.reddit.com/gallery/15wdvhr)

redirects to

[https://old.reddit.com/gallery/15wdvhr](https://old.reddit.com/gallery/15wdvhr)

but with a page not found error.  I don't think there's an old.reddit.com equivalent for these gallery pages.

Thanks for your work on this userscript!

**Comment by RichKMLS** [comment]
I ran into the same problems you were facing and I've excluded these types of URLs from the script. Let me know if you run into other issues. Thanks for pointing this out!
