### ISSUE TITLE
Issue when using Reddit Android app

### ISSUE THREAD

**Issue by Dr-Battenburg** [RichKMLS/Old-Reddit-Redirect#4]
Hello,

I have this script installed in Adguard on Android. Sometimes I use the reddit app, sometimes I view reddit in Chrome, which is when this script becomes handy.

I have a problem when using the app: when I click a link to an external site it doesn't load it, it just stays on a loop trying to load the page. It's stuck looping on "out reddit.com". When I disable the script there's no problem.

I know my use-case is probably odd because I'm hopping between the app and Chrome. But if you can offer any assistance I'd appreciate it.

Thanks!

**Comment by RichKMLS** [comment]
I added a line to ignore out.reddit.com URLs so I think this script should work for you now. Also, it appears that out.reddit.com is used to track your outbound clicks for ad personalization and it can be disabled in your [reddit preferences](https://www.reddit.com/prefs/#allow_clicktracking). Not sure what options you have in the app but I would recommend disabling it regardless of whether or not the script works. 😊

Thanks for sharing your issue and let me know if you run into future issues.

**Comment by RichKMLS** [comment]
Closing this issue.

**Comment by Dr-Battenburg** [comment]
It works! Thank you, you are a badass.
