### ISSUE TITLE
Reddit keep reloading

### ISSUE THREAD

**Issue by thiendt2k1** [RichKMLS/Old-Reddit-Redirect#5]
Hi, first of all, thanks you for your fine work, did me a favor a couple of month now, work perfectly without error.
Until today, when reddit keep returning to new layout causing reload, it cant load page unless disable the script, after disabled, the site load the newest layout, then i enabled again and refresh how many is ok, but not as first time.
Step to reproduce: 
Use violentmonkey on Chrome/Edge
Rewrite reddit.com to new.reddit.com
open a new reddit tab
Problem
Disable, reload, page load OK
reload the same tab, OK
Open new tab, Problem

Here is your script modified to the newer layout:
![image](https://github.com/RichKMLS/Old-Reddit-Redirect/assets/58879301/c12971f0-7b83-4705-8ec4-059281d513a2)

Thanks for your time!
Sincerely.

**Comment by KuryKat** [comment]
@thiendt2k1 I made a fork of this project to redirect to the `new.reddit.com`, [you can find it here](https://github.com/KuryKat/New-Reddit-Redirect/)

You should check it out! I fixed all the current "infinite reloading" issues that I could find, and improved the code a little bit.

You could always report any new issues on there if you choose to use it!

**Comment by thiendt2k1** [comment]
tks, the script is working smoothly as of now, i'm closing this.
